Kapitel-16/bookmakrs_ajax/config/routes.rb
BookmakrsAjax::Application.routes.draw do
  resources :bookmarks

end

Kapitel-16/bookmakrs_ajax/app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
end

Kapitel-16/bookmakrs_ajax/app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  # GET /bookmarks
  # GET /bookmarks.json
  def index
    @bookmarks = Bookmark.all
    @bookmark = Bookmark.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bookmarks }
    end
  end

  # GET /bookmarks/1
  # GET /bookmarks/1.json
  def show
    @bookmark = Bookmark.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bookmark }
    end
  end

  # GET /bookmarks/new
  # GET /bookmarks/new.json
  def new
    @bookmark = Bookmark.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bookmark }
    end
  end

  # GET /bookmarks/1/edit
  def edit
    @bookmark = Bookmark.find(params[:id])
  end

  # POST /bookmarks
  # POST /bookmarks.json
  def create
    @bookmark = Bookmark.new(params[:bookmark])
    @bookmark.save
    respond_to do |format|
      format.js
    end
  end

  # PUT /bookmarks/1
  # PUT /bookmarks/1.json
  def update
    @bookmark = Bookmark.find(params[:id])

    respond_to do |format|
      if @bookmark.update_attributes(params[:bookmark])
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmarks/1
  # DELETE /bookmarks/1.json
  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    respond_to do |format|
      format.html { redirect_to bookmarks_url }
      format.json { head :ok }
      format.js
    end
  end
end

Kapitel-16/bookmakrs_ajax/app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

Kapitel-16/bookmakrs_ajax/app/views/bookmarks/_bookmark.html.erb
<%= content_tag_for(:tr, bookmark) do %>
  <td><%= bookmark.title %></td>
  <td><%= bookmark.url %></td>
  <td><%= link_to 'Show', bookmark %></td>
  <td><%= link_to 'Edit', edit_bookmark_path(bookmark) %></td>
  <td><%= link_to 'Destroy', bookmark, method: :delete, remote: true %></td>
<% end %>

Kapitel-16/bookmakrs_ajax/app/views/bookmarks/_form.html.erb
<%= form_for(@bookmark, remote: true) do |f| %>
  <% if @bookmark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2>

      <ul>
      <% @bookmark.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Kapitel-16/bookmakrs_ajax/app/views/bookmarks/create.js.erb
$('table').append('<%= j render @bookmark %>');
$('#<%= dom_id(@bookmark) %>').effect('highlight',{}, 2000);
$('form :text').val("");

Kapitel-16/bookmakrs_ajax/app/views/bookmarks/destroy.js.erb
$('#<%= dom_id(@bookmark) %>').fadeOut();

Kapitel-16/bookmakrs_ajax/app/views/bookmarks/edit.html.erb
<h1>Editing bookmark</h1>

<%= render 'form' %>

<%= link_to 'Show', @bookmark %> |
<%= link_to 'Back', bookmarks_path %>

Kapitel-16/bookmakrs_ajax/app/views/bookmarks/index.html.erb
<h1>Listing bookmarks</h1>

<%= render 'form' %>

<table>
  <tr>
    <th>Title</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <%= render @bookmarks %>
</table>

Kapitel-16/bookmakrs_ajax/app/views/bookmarks/new.html.erb
<h1>New bookmark</h1>

<%= render 'form' %>

<%= link_to 'Back', bookmarks_path %>

Kapitel-16/bookmakrs_ajax/app/views/bookmarks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @bookmark.title %>
</p>

<p>
  <b>Url:</b>
  <%= @bookmark.url %>
</p>


<%= link_to 'Edit', edit_bookmark_path(@bookmark) %> |
<%= link_to 'Back', bookmarks_path %>