Kapitel-05/bookmarkmanager_ohne_i18n/config/routes.rb
Bookmarkmanager::Application.routes.draw do

  resources :bookmarks
  resources :users, only: [:new, :create]
  
  get "login" => "sessions#new", as: "login"
  post "sessions" => "sessions#create", as: "sessions"
  delete "logout" => "sessions#destroy", as: "logout"  
  root to: 'pages#home'
  
  

end

Kapitel-05/bookmarkmanager_ohne_i18n/app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :user
  validates :title, :url, presence: true
end

Kapitel-05/bookmarkmanager_ohne_i18n/app/models/user.rb
class User < ActiveRecord::Base
  has_many :bookmarks
  has_secure_password
  validates :email, format: /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i, uniqueness: true
end

Kapitel-05/bookmarkmanager_ohne_i18n/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  private
  
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

  def user_signed_in?
    current_user.present?
  end
  
  helper_method :user_signed_in?  
end

Kapitel-05/bookmarkmanager_ohne_i18n/app/controllers/bookmarks_controller.rb
# encoding: utf-8

class BookmarksController < ApplicationController
  before_filter :require_login
  def index
    @bookmarks = current_user.bookmarks
  end
  
  def show
    @bookmark = current_user.bookmarks.find(params[:id])
  end
  
  def edit
     @bookmark = current_user.bookmarks.find(params[:id])
  end
  
  def new
    @bookmark = current_user.bookmarks.build
  end
  
  def create
    @bookmark = current_user.bookmarks.build(params[:bookmark])
    if @bookmark.save
      redirect_to bookmarks_path, notice: 'Favorit wurde erfolgreich angelegt.'
    else
      render "new"
    end
  end
  
  def update
    @bookmark = current_user.bookmarks.find(params[:id])
    if @bookmark.update_attributes(params[:bookmark])
      redirect_to bookmarks_path, notice: 'Favorit wurde erfolgreich geändert.'
    else
      render "edit"
    end
  end
  
  def destroy
    @bookmark = current_user.bookmarks.find(params[:id])
    @bookmark.destroy
    redirect_to bookmarks_url, notice: 'Favorit wurde erfolgreich gelöscht.'
  end  

  private
  
  def require_login
    unless user_signed_in?
      redirect_to login_path, alert: "Bitte melden Sie sich zuerst an."
    end
  end
end

Kapitel-05/bookmarkmanager_ohne_i18n/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to bookmarks_path, notice: "Sie haben sich angemeldet!"
    else
      flash.now.alert = "Fehlerhafte E-Mail-Adresse oder Passwort"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Sie haben sich abgemeldet!"
  end
end

Kapitel-05/bookmarkmanager_ohne_i18n/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to login_path, notice: "Ihr Benutzerkonto wurde angelegt!"
    else
      render "new"
    end
  end
end

Kapitel-05/bookmarkmanager_ohne_i18n/app/helpers/bookmarks_helper.rb
# encoding: utf-8
module BookmarksHelper
  def back_to_list
    content_tag(:p, link_to("Zurück zur Liste", bookmarks_path), class: "subNavigation")
  end
end

Kapitel-05/bookmarkmanager_ohne_i18n/app/helpers/sessions_helper.rb
module SessionsHelper
end

Kapitel-05/bookmarkmanager_ohne_i18n/app/helpers/users_helper.rb
module UsersHelper
end

Kapitel-05/bookmarkmanager_ohne_i18n/app/views/bookmarks/_bookmark.html.erb
<li>
  <%= link_to bookmark.title, bookmark.url %>
  (<%= link_to "Details", bookmark_path(bookmark) %> |
  <%= link_to "ändern", edit_bookmark_path(bookmark) %> |
  <%= link_to 'löschen', bookmark,
      confirm: 'Wollen Sie diesen Datensatz wirklich löschen?',
      method: :delete %>)
</li>

Kapitel-05/bookmarkmanager_ohne_i18n/app/views/bookmarks/_form.html.erb
<%= form_for(@bookmark) do |f| %>
  <% if @bookmark.errors.any? %> 
    <ul>
    <% @bookmark.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  <% end %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :url %>
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.label :comment %>
    <%= f.text_area :comment %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

Kapitel-05/bookmarkmanager_ohne_i18n/app/views/bookmarks/edit.html.erb
<% @title = "bearbeiten" %>
<h2>Favorit bearbeiten</h2>
<%= render "form" %>
<%= back_to_list %>

Kapitel-05/bookmarkmanager_ohne_i18n/app/views/bookmarks/index.html.erb
<% @title = "Liste" %>
<h2>Liste der Favoriten</h2>
<ul>
<%= render @bookmarks %>
</ul>

<p><%= link_to "Neuen Favorit erstellen", new_bookmark_path %></p>

Kapitel-05/bookmarkmanager_ohne_i18n/app/views/bookmarks/new.html.erb
<% @title = "neu" %>
<h2>Neuen Favorit erstellen</h2> 
<%= render "form" %>
<%= back_to_list %>

Kapitel-05/bookmarkmanager_ohne_i18n/app/views/bookmarks/show.html.erb
<h2>Detail zum Favorit</h2>

<p>
  <b>Titel:</b>
  <%= @bookmark.title %>
</p>

<p>
  <b>URL:</b>
  <%= @bookmark.url %>
</p>
<p>
  <b>Kommentar:</b>
  <%= @bookmark.comment %>
</p>

<p>
  <b>Erstellt am:</b>
  <%= @bookmark.created_at %>
</p>

<p>
  <b>Geändert am:</b>
  <%= @bookmark.updated_at %>
</p>

<%= back_to_list %>

Kapitel-05/bookmarkmanager_ohne_i18n/app/views/users/new.html.erb
<h2>Neuen Benutzer anlegen</h2>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  <% end %>
  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </p>
  <p><%= f.submit %></p>
<% end %>    